# Site wide configuration

title: Francesco Santagati
description: Portfolio
logo: lechuck.jpg # 120x120 px default image used for Twitter summary card
teaser: lechuck.jpg # 400x250 px default teaser image used in image archive grid
locale: it
#url: http://francescosantagati.github.io
url: http://192.168.33.10:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Francesco Santagati
  email: francesco@santagati.it
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: lechuck.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
