# Site settings
title: Francesco Santagati
email: francesco@santagati.it
url: https://francescosantagati.github.io
description: "Portfolio and projects"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Francesco Santagati
  location: Location
  social: Around the Web
#  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: https://bitbucket.org/scunsaiocu
  - title: github
    url: https://github.com/FrancescoSantagati
  - title: linkedin
    url: http://it.linkedin.com/pub/francesco-santagati/68/1b0/947
  - title: android
    url: https://play.google.com/store/apps/developer?id=Francesco+Santagati

# Postal address (add as many lines as necessary)
address:
  - line: Turin, Italy
#  - line: Beverly Hills, CA 90210

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
